sonar.projectKey=secureauth-devsecops-pipeline
sonar.projectName=SecureAuth DevSecOps Pipeline
sonar.sources=backend,frontend/src
sonar.tests=tests,frontend/tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.exclusions=frontend/node_modules/**,frontend/dist/**,docs/**,**/__pycache__/**
sonar.python.coverage.reportPaths=reports/backend-coverage.xml
