apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
configMapGenerator:
  - name: secureauth-config
    literals:
      - APP_ENV=development
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_TIMEOUT_SECONDS=10
      - RATE_LIMIT_MAX_REQUESTS=30
generatorOptions:
  disableNameSuffixHash: true

